# Generated by Django 5.0.6 on 2024-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Ayush Tripathi", max_length=20)),
                ("brief_intro", models.TextField()),
                ("profile_picture_path", models.FilePathField()),
                ("banner_picture_path", models.FilePathField()),
                ("paragraph_description", models.TextField()),
            ],
        ),
    ]
