# Generated by Django 5.0.6 on 2024-05-30 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="introduction",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 30, 21, 3, 31, 381883, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="banner_picture_path",
            field=models.FilePathField(path="/home"),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="profile_picture_path",
            field=models.FilePathField(path="/home"),
        ),
    ]
