# Generated by Django 5.0.6 on 2024-06-01 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_introduction_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="introduction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
